[[program]]
name = "MinglingCLI"
dispatchers = [
    "src/add_dispatcher.rs"
]

[[dispatcher]]
bind = "MinglingCLI"
name = "AddDispatcherCommand"
route = "AddDispatcherEntry"

[[chain]]
bind = "MinglingCLI"
name = "ParseAddDispatcherArgument"
mount = "AddDispatcherEntry"
